version: '3'

volumes:
  mysql_data:
  node_modules:

services:
  web:
    build:
      context: ./docker
    volumes:
      - ${PROJECT_PATH}:/var/www/html:cached
      - node_modules:/var/www/html/node_modules
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - mysql
 
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
      - ${DB_PORT}:3306
    command: --innodb-use-native-aio=0
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
       - ${PMA_PORT}:80
    volumes:
       - /sessions